Import('env')


prog = env.Program('stage9',
                source = 'extra_example', 
                LIBS = ['hal', 'ehgk_page'], 
                LIBPATH = [
                    '#.pio/build/STC15W204S/lib/hal',
                    '#.pio/build/STC15W204S/lib/ehgk_page'
                    ])

env.Default (
    env.Object('extra_example'),
    prog,
    env.Install('#firmware', prog)
), 