[package]
name=led_unittests
version=1.0.0

[target]
programs=led_unittests

[compiler]
unitdir=. $(LAZARUS_BASE)/lcl/interfaces/qt6/* $(LAZARUS_BASE)/components/fpcunit/* $(LAZARUS_BASE)/packager/units/$(CPU_TARGET)-$(OS_TARGET) $(LAZARUS_BASE)/components/* $(LAZARUS_BASE)/lcl/units/$(CPU_TARGET)-$(OS_TARGET) $(LAZARUS_BASE)/lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM) ./../
options=-MObjFPC -Scghi -O1 -g -gl -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) $(DBG_OPTIONS)


[require]
# List required FPC packages (e.g., FCL for database or logic)
packages=rtl paszlib fcl-process hash libtar fpmkunit fcl-base fcl-fpcunit

[install]
fpcversion=3.2.0

[default]
# Target operating system and CPU (optional, can be passed via command line)
cpu=x86_64
os=linux

[prerules]
# LCL Platform
ifndef LCL_PLATFORM
ifeq ($(OS_TARGET),win32)
LCL_PLATFORM=win32
else
ifeq ($(OS_TARGET),win64)
LCL_PLATFORM=win32
else
ifeq ($(OS_TARGET),darwin)
LCL_PLATFORM=cocoa
else
LCL_PLATFORM=nogui
endif
endif
endif
endif
export LCL_PLATFORM

ifndef LAZARUS_BASE
LAZARUS_BASE=/usr/share/lazarus/2.2.6
endif
export LAZARUS_BASE



# fpcmake -Tall -w
# make clean all LCL_PLATFORM=gtk2
# make clean all && make clean all -C ./test LCL_PLATFORM=gtk2

