Import('env')

prog = env.Program('stage3',
                source = 'line0_timer', 
                LIBS = ['hal'], 
                LIBPATH = [
                    '#.pio/build/STC15W204S/lib/hal'])

env.Default (
    env.Object('line0_timer'),
    prog,
    env.Install('#firmware', prog)
), 