/** 
 * @file led_timer.c
 * 
 * @brief STC electronic hourglass kit. Stage 2.
 * 
 * @details
 * This example demostrate how to put ON one LED L1 using timer0
 * 
 * L1 anode is connected to P30 pin and L1 cathode is connected to P10.
 * To putting ON the P30 pin should be HIGH and P10 should be LOW.
 * Other pins should be in high impedance mode (input-only STC15 pin mode). 
 *
 * To limit current consumption, the LED blinks almost imperceptibly to the human eye.
 * 
 * Main function init and start timer0 in mode0 (16-bit reloadable timer).
 * Timer interrupt service routine (ISR) on interrupt calls swith L1 on/off.
 * 
 * This example use STC15 HAL library from https://github.com/mgoblin/STC15lib.
 * 
 * @author Michael Golovanov (mike.golovanov@gmail.com)
 */

/*======================== STC15 HAL headers ====================================*/
#include <sys.h>
#include <pin.h>
#include <timer0_mode0.h>
/*========================End of STC15 HAL headers ==============================*/

#include <leds1.h> // custom library header for led pins manipulations 

/*=============================== Timer0 ISR =====================================*/

#define TIMER_TICKS 0xFFFF // Timer0 ticks count uint16_t

__bit is_led_1_on = 0; // L1 On/Off bit flag 

/**
 * @brief Timer0 interrupt serivce routine
 * 
 * @details
 * Interupt 1 is timer0 interrupt. ISR is naked - therefore doesnt save registers and 
 * have reti generated by SDCC compiler. 
 * 
 * reti should be add explicitly as last statement in 
 * ISR.
 * 
 * This version of ISR doesnt use any registers.
 * 
 * ISR on each call analyze its previous state and change it to the next state.
 * ISR has two states - all leds off / led L1 on. 
 */
void timerISR() __interrupt(1) __naked
{
    // Change states between all leds off / L1 is on
    is_led_1_on ? leds_off() : led_1_on();
    // Save state in bit flag for next calls
    is_led_1_on = !is_led_1_on;

    // Explicit reti (return from interrupt) needed because ISR declared with 
    // __naked modifier
    __asm reti __endasm;
}
/*=========================== End of Timer0 ISR ==================================*/

/**
 * @brief Main function. Firmware code entry point.
 * 
 * @details
 * Init and start Timer0 in mode0 (16-bit auto reloadable timer).
 * 
 * After timer0 started sleep in endless cycle.
 */
void main()
{
    timer0_mode0_1T_init();
    timer0_mode0_start(TIMER_TICKS);

    while (1) {}
}