Import('env')

prog =    env.Program('stage2',
                source = 'led_timer', 
                LIBS = ['leds1', 'hal'], 
                LIBPATH = [
                    '#.pio/build/STC15W204S/lib/leds1', 
                    '#.pio/build/STC15W204S/lib/hal'])


env.Default (
    env.Object('led_timer'),
    prog,
    env.Install('#firmware', prog)
), 