name: Build Lazarus EGHK UI Editor

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Also supports windows-latest and macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: sxmxta/lazarus@v1.0.18
      with:
        lazarus-version: "2.2.6"
        with-cache: false
        
    - run: lazbuild src/utils/ui_editor/lazarus/led_control/ledcontrol.lpk
    - run: lazbuild --add-package-link=src/utils/ui_editor/lazarus/led_control/ledcontrol.lpk /src/utils/ui_editor/lazarus/led_control/led_unittest.lpi
    - run: ./led_unittests --all --format=XML --file=result.xml
