name: Build Lazarus EGHK UI Editor

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Also supports windows-latest and macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Lazarus
        uses: sxmxta/lazarus@v1.0.18
        with:
          lazarus-version: 'stable' # or a specific version like '2.2.6'
