name: Build Lazarus EGHK UI Editor

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # Also supports windows-latest and macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: sxmxta/lazarus@v1.0.18
      with:
        lazarus-version: "stable"
        include-packages: "Synapse 40.1"
        with-cache: true
    - run: lazbuild YourTestProject.lpi
    - run: YourTestProject
